### ISSUE TITLE
One entire string for one translation item

### ISSUE THREAD

**Issue by Xottab-DUTY** [halvors/Nuclear-Physics#10]
Please, don't use two strings for one item.

For example:
Deuterium Cell – mod takes `fluid.deuterium` and `item.nuclearphysics.cell.name` strings. (or maybe other strings, I don't know)

In English there's no problem. But in other languages this may cause translation problems.

For example, Russian translation for Deuterium Cell is dumb and I can't do anything with that =(

For fixing this you just need to provide strings for every item, like:
```
item.nuclearphysics.cell.name
item.nuclearphysics.cellWater.name
item.nuclearphysics.cellDeuterium.name
```

Thanks in advance.

P.S. and sorry for the mess here. I could write better text for this issue, but okay...

**Comment by halvors** [comment]
@Xottab-DUTY Hmm, i understand the translation issue. But the issue is that the cell can dynamically be filled with fluid. Like the vanilla bucket. And that is using 2 strings for 1 entry right? Like "Water Bucket", so i'm unable to understand how i can keep compatibility with fluids from other mods dynamically if not merging strings :( The cell is known, but the fluid in the cell is not always known...

**Comment by Xottab-DUTY** [comment]
Oh, I don't think about that..
Well, I think the best decision for cells would be naming it "Cell" and point the fluid in the tooltip, like
```
item.nuclearphysics.cell.name = Cell
item.nuclearphysics.cell.tooltip = Contains: %fluidName%
```
or the other variant would be point fluid in name, but it's not the best (the above is better):
```
item.nuclearphysics.cell.name = Cell (contains: %fluidName%)
or
item.nuclearphysics.cell.name = Cell (%fluidName%)
```

**Comment by halvors** [comment]
@Xottab-DUTY That is a great idea, i think we should solve the prolem that way :-)

**Comment by Xottab-DUTY** [comment]
@halvors Good! Will be waiting for you and then will update my PR

**Comment by halvors** [comment]
@Xottab-DUTY Done, i'll merge as soon as your PR is updated.

**Comment by Xottab-DUTY** [comment]
@halvors Just force pushed the update. The PR is ready =)

**Comment by halvors** [comment]
Will do, thanks :)
