### ISSUE TITLE
NoClassDefFoundError: ItemWrench

### ISSUE THREAD

**Issue by gunboy001** [halvors/Nuclear-Physics#3]
Game crashes on startup with nuclearphysics installed, I use foamfix from aise and both with and without it the game crashes with the same error (I don't know why I thought it would have had an effect but I tried it anyways).
Here are the crash reports:
https://pastebin.com/E3z6p6Ca
https://pastebin.com/csk1XC7M

**Comment by halvors** [comment]
@gunboy001 Thanks for your bug report. I'll fix this as soon as possible.

**Comment by halvors** [comment]
If you want to be able to play in the meantime, install mekanism. That should solve the issue. But this is still a bug since mekakism should not be a dependency.

**Comment by halvors** [comment]
Fixed in commit c6b9f0a7cecfa6c18e90570f729d77857886cb9c

**Comment by halvors** [comment]
@gunboy001 Try the latest version :)

**Comment by gunboy001** [comment]
That was fast, thanks!
