### ISSUE TITLE
[1.10.2] "Exception in server tick loop" when inserting Plasma into a Reactor Cell

### ISSUE THREAD

**Issue by ACGaming** [halvors/Nuclear-Physics#7]
- Minecraft 1.10.2
- Forge 12.18.3.2422 (also crashes with other versions)
- Nuclear Physics 0.1.19 (also crashes with other versions)

https://paste.ubuntu.com/25606199/

**Comment by halvors** [comment]
@ACGaming Thanks for reporting! This is now fixed in the latest build, see: https://minecraft.curseforge.com/projects/nuclear-physics/files/2483722
